#!/usr/bin/env python

from os import path, system
from subprocess import call, check_output, CalledProcessError
import sys


def open_file(filename):
    call(['xdg-open', filename])


if __name__ == '__main__':
    pattern = '*%s*' % ('*'.join(sys.argv[1:]))

    try:
        items = check_output(['locate', '-b', '-i', pattern])[:-1].split('\n')

        if len(items) == 1:
            open_file(items[0])
        else:
            for i in range(1, len(items) + 1):
                print '[%d]' % i, path.basename(items[i - 1])

            item_no = int(raw_input("\nWhich file to open: "))
            open_file(items[item_no - 1])
    except CalledProcessError:
        print "File(s) not found."
    except:
        pass
