#!/usr/bin/env python

from os import path, system
from subprocess import call, check_output

import sys


BASENAME = 0
DIR = 1


def open_file(filename):
    call(['xdg-open', filename])


def locate(terms, mode=BASENAME, ignorecase=True):
    options = []

    if mode == BASENAME:
        pattern = '*%s*' % '*'.join(terms)
        options.append('-b')
    elif mode == DIR:
        pattern = '*%s' % '*'.join(terms)

    if ignorecase:
        options.append('-i')

    cmd = ['locate']
    cmd.extend(options)
    cmd.append(pattern)

    try:
        return check_output(cmd)[:-1].split('\n')
    except:
        return []


if __name__ == '__main__':
    mode = sys.argv[1].startswith('/') and DIR or BASENAME
    items = locate(sys.argv[1:], mode=mode)

    if len(items) == 0:
        print "File(s) not found."

    elif len(items) == 1:
        open_file(items[0])

    else:
        for i in range(1, len(items) + 1):
            print '[%d]' % i, items[i - 1]

        try:
            item_no = int(raw_input("\nWhich file to open: "))
            open_file(items[item_no - 1])

        except:
            pass
