#!/usr/bin/env python

from __future__ import print_function
from subprocess import call, check_output, Popen
from os.path import isdir
from os import system

import argparse
import sys


def open_file(filepath):
    call(['xdg-open', filepath])


def copy_to_xclip(filepath):
    system('echo -n %s | xclip' % filepath)


def copy_to_xsel(filepath):
    system('echo -n %s | xsel' % filepath)


def write_path(filepath):
    with open(args.write, 'w') as out:
        out.write(filepath)


def locate(terms, is_directory, case_sensitive):
    options = []

    pattern = '*' + '*'.join(terms)

    if not is_directory:
        pattern += '*'
        options.append('--basename')

    if not case_sensitive:
        options.append('--ignore-case')

    cmd = ['locate'] + options + [pattern]

    try:
        items = check_output(cmd)[:-1].split('\n')
    except:
        items = []

    return [_ for _ in items if isdir(_)] if is_directory else items


def show_candidates(items):
    try:
        from termcolor import colored

        for i in range(1, len(items) + 1):
            print(colored('[%d] ' % i, 'yellow', attrs=['bold']), end='')
            print(items[i - 1])

    except:
        for i in range(1, len(items) + 1):
            print('[%d]' % i, items[i - 1])


def select_item(items, action):
    if len(items) == 1:
        action(items[0])
    else:
        show_candidates(items)
        item_no = int(raw_input("\nChoose one file to open: "))
        action(items[item_no - 1])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Find and open files easily.')

    parser.add_argument('terms',
                        metavar='term',
                        nargs='+',
                        help='The terms to search with')

    parser.add_argument('-d', '--directory',
                        action='store_true',
                        help='Search for directories instead of files')

    parser.add_argument('-c', '--case-sensitive',
                        action='store_true',
                        help='Enable case sensitive search')

    group = parser.add_mutually_exclusive_group()

    group.add_argument('-x', '--xclip',
                       action='store_true',
                       help='Copy full path of seleted item to X clipboard')

    group.add_argument('-s', '--xsel',
                       action='store_true',
                       help='Copy full path of seleted item to X selection')

    group.add_argument('-w', '--write',
                       metavar='file',
                       action='store',
                       help='Write full path of seleted item to `file\'')

    args = parser.parse_args()
    items = locate(args.terms, args.directory, args.case_sensitive)

    if len(items) == 0:
        print("File(s) not found.")
        sys.exit(1)

    try:
        if args.xclip:
            action = copy_to_xclip
        elif args.xsel:
            action = copy_to_xsel
        elif args.write != None:
            action = write_path
        else:
            action = open_file

        select_item(items, action)
    except:
        pass
